
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Feb 06 03:39:35 ALMT 2017
//----------------------------------------------------

package lang_processor;

/** CUP generated class containing symbol constants. */
public class TokenType {
  /* terminals */
  public static final int SEMICOLON = 3;
  public static final int RIGHTBRACKET = 5;
  public static final int PLUS = 6;
  public static final int THEN = 19;
  public static final int EQUAL = 14;
  public static final int WHILE = 20;
  public static final int INITIALIZE = 15;
  public static final int STAR = 8;
  public static final int SLASH = 9;
  public static final int SIGN = 12;
  public static final int END = 17;
  public static final int IF = 18;
  public static final int RCBRACKET = 11;
  public static final int DO = 21;
  public static final int BEGIN = 16;
  public static final int EOF = 0;
  public static final int LEFTBRACKET = 4;
  public static final int MINUS = 7;
  public static final int error = 1;
  public static final int ARROW = 13;
  public static final int INTEGER = 23;
  public static final int TO = 22;
  public static final int ASMT_SYMBOL = 2;
  public static final int LABEL = 24;
  public static final int LCBRACKET = 10;
}

